### ISSUE TITLE
again another error

### ISSUE THREAD

**Issue by fdsmjkfjires** [addi00000/empyrean#10] opened 2022-06-08 14:41 UTC
![image](https://user-images.githubusercontent.com/96617924/172645007-81f7e65d-6b89-461a-a8ee-e19760620130.png)
when i run the exe this is the message that pops up in the webhook

**Comment by addi00000** [comment] 2022-06-10 14:45
Duplicate of #1 
Working to fix.

**Closed by addi00000** 2022-06-10 14:45 UTC
Labels: bug, duplicate
