### ISSUE TITLE
iv got a REAL ISSUE this time im sorry for the other issues i opned 

### ISSUE THREAD

**Issue by fdsmjkfjires** [addi00000/empyrean#8] opened 2022-06-07 16:36 UTC
<img width="294" alt="image" src="https://user-images.githubusercontent.com/96617924/172435598-65817ceb-cb40-4d4e-89cd-cd73d858802e.png">
this is the error i get if i run the exe

**Comment by fdsmjkfjires** [comment] 2022-06-07 16:49
> Seems to be an error with payment method detections.
> 
> Do you have billing on your account? If so what type?
> 
> Thanks for alerting me will fix asap.

i dont have billing but i do have nitro

**Comment by addi00000** [comment] 2022-06-10 14:45
Duplicate of #1 
Working to fix.

**Closed by addi00000** 2022-06-10 14:45 UTC
Labels: bug, duplicate
